### ISSUE TITLE
Unexpected text "hii" found in console

### ISSUE THREAD

**Issue by Paul-Negru** [peviitor-ro/qa#109]
SEVERITY:  LOW

**ENVIRONMENT**: PROD
   URL: https://peviitor.ro/
   browser: Google Chrome

**STEPS TO REPRODUCE**

1.  open URL in browser
2.  open Console

**EXPECTED RESULTS**
- no message shown in console

**ACTUAL RESULTS**
- text "hii" found in console

**Comment by sebiboga** [comment]
https://peviitor.testquality.com defect [D3](https://peviitor.testquality.com/project/12763/result/2537828/defect/8557).
